config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :categories, except: [:show] do
    resources :themes do
      member do
        post   :vote_for
        post   :vote_against
        delete :revote
      end
      collection do
       get :autocomplete
      end
      resources :comments, except: [:index, :show] do
        resources :subcomments, except: [:index, :show]
      end
    end
  end

  root 'pages#home'

  get 'themes/new', to: 'themes#new_separate', as: :new_separate
  post 'themes/create', to: 'themes#create_separate', as: :create_separate

  get '/statistics', to: 'pages#statistics', as: :statistics

  get '/change_locale/:locale', to: 'sessions#change_locale', as: :change_locale

  get '*path', to: redirect('/')

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  scope :root_comments, -> { where(root_comment_id: nil) }

  has_many   :subcomments, class_name: 'Comment', foreign_key: 'root_comment_id', dependent: :destroy
  belongs_to :theme
  belongs_to :user

  validates :content, presence: true, length: { maximum: 500 }

  def root_comment?
    root_comment_id.nil?
  end

  def editable?
    created_at > (Time.now - 5.minutes)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_category, except: [:index, :show]
  before_action :set_theme, except: [:index, :show]
  before_action :set_comment, only: [:edit, :update, :destroy]
  respond_to    :js, only: [:edit, :destroy]

  def new
    @comment = @theme.comments.new
    authorize @comment
  end

  def create
    authorize Comment
    @comment = @theme.comments.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      flash[:success] = t('.success')
    else
      flash[:error] = t('.error')
    end
    redirect_to :back
  end

  def edit; end

  def update
    authorize @comment
    if @comment.editable? || current_user.admin? || current_user.moderator?
      if @comment.update_attributes(comment_params)
        flash[:success] = t('.success')
      else
        flash[:error] = t('.error')
      end
    else
      flash[:error] = t('.can_t_edit')
    end
    redirect_to :back
  end

  def destroy
    authorize @comment
    if @comment.destroy
      flash.now[:success] = t('.success')
    else
      flash.now[:error] = t('.error')
    end
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_theme
    @theme = @category.themes.find(params[:theme_id])
  end

  def set_comment
    @comment = @theme.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper; end

app/views/comments/_comment.html.slim
.comment-body class = "comment-#{comment.id}-body"
  .header
    span
      = image_tag comment.user.avatar.thumb, alt: "User's avatar", class: 'avatar small'
      b = comment.user.username
    = t('.commented', time: time_ago_in_words(comment.created_at))

  .content
    p = comment.content

  - if current_user
    .links.comment
      = link_to '', new_category_theme_comment_subcomment_path(@category, @theme, comment),
                remote: true,
                class: 'glyphicon glyphicon-share-alt green comment-reply'
      // TODO: Needs refactoring
      - if comment.editable? && (current_user == comment.user) || current_user.admin? || current_user.moderator?
        = link_to '', edit_category_theme_comment_path(@category, @theme, comment),
                class: 'glyphicon glyphicon-pencil comment-edit',
                remote: true
      - if (current_user == comment.user) || current_user.admin? || current_user.moderator?
        = link_to '', category_theme_comment_path(@category, @theme, comment),
                method: :delete,
                data: { confirm: t('.delete') },
                class: 'glyphicon glyphicon-trash red comment-delete',
                remote: true

- if comment.subcomments.present?
  ul
    = render(partial: 'comments/comments_template', locals: { comments: comment.subcomments })

app/views/comments/_comments_template.html.slim
- comments.each do |comment|
  - if comment.root_comment?
    li class = 'comment-#{comment.id}'
      = render(partial: 'comments/comment', locals: { comment: comment })
  - else
    li class = 'child-comment comment-#{comment.id}'
      = render(partial: 'comments/comment', locals: { comment: comment })

app/views/comments/_form.html.slim
= simple_form_for [@category, @theme, @comment], html: { class: 'comment-form text-center' } do |t|
  = t.input :content, as: :text, input_html: { rows: 2 }, autofocus: true, label: false, placeholder: t('.content')
  = t.submit t('buttons.update'), class: 'btn btn-success'
  = link_to t('buttons.cancel'), :back, class: 'btn btn-default'

app/views/comments/destroy.js.slim
- if @comment.destroyed?
  | $('.comment-#{@comment.id}').html("<div class='alert alert-success text-center'>#{flash[:success]}</div>").fadeOut(3000);
- else
  | $('.comment-#{@comment.id}').prepend("<div class='alert alert-error'>#{flash[:error]}</div>");

app/views/comments/edit.js.slim
| $('.comment-#{@comment.id}-body').replaceWith('#{j render(partial: 'comments/form')}').fadeIn(500)