config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :categories, except: [:show] do
    resources :themes do
      member do
        post   :vote_for
        post   :vote_against
        delete :revote
      end
      collection do
       get :autocomplete
      end
      resources :comments, except: [:index, :show] do
        resources :subcomments, except: [:index, :show]
      end
    end
  end

  root 'pages#home'

  get 'themes/new', to: 'themes#new_separate', as: :new_separate
  post 'themes/create', to: 'themes#create_separate', as: :create_separate

  get '/statistics', to: 'pages#statistics', as: :statistics

  get '/change_locale/:locale', to: 'sessions#change_locale', as: :change_locale

  get '*path', to: redirect('/')

end

app/models/theme.rb
class Theme < ActiveRecord::Base

  belongs_to :category
  belongs_to :user
  belongs_to :city

  has_many   :comments, dependent: :destroy

  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :content, presence: true, length: { maximum: 3000 }
  validates :city_id, presence: true

  before_save :capitalize_title

  acts_as_voteable

  searchkick word_start: [:title]

  def capitalize_title
    self.title = title.capitalize
  end

end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show, :autocomplete]
  before_action :set_category, except: [:new_separate, :create_separate]
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  helper_method :current_city

  def index
    if params[:query].present?
      @themes = Theme.search params[:query],
      page: params[:page],
      where: { category_id: params[:category_id] }
    else
      @themes = Theme.where(category_id: params[:category_id])
      @themes = @themes.page(params[:page]).per(10)
    end
  end

  def new
    @theme = @category.themes.new
    authorize @theme
  end

  def new_separate
    @theme = Theme.new
    @categories = Category.all
    authorize @theme
  end

  def show
    @root_comments = @theme.comments.root_comments
  end

  def edit; end

  def create
    authorize Theme
    @theme = @category.themes.new(theme_params)
    @theme.user_id = current_user.id

    if @theme.save
      redirect_to category_theme_path(@category, @theme), success: t('.success', theme: @theme.title)
    else
      flash.now[:error] = t('.error')
      render :new
    end
  end

  def create_separate
    @theme = current_user.themes.new(theme_params)
    authorize @theme
    if @theme.save
      redirect_to category_theme_path(@theme.category, @theme), success: t('.success', theme: @theme.title)
    else
      flash.now[:error] = t('.error')
      render :new_separate
    end
  end

  def update
    authorize @theme
    if @theme.update_attributes(theme_params)
      redirect_to category_theme_path(@category, @theme), success: t('.success', theme: @theme.title)
    else
      flash.now[:error] = t('.error')
      render :edit
    end
  end

  def destroy
    authorize @theme
    if @theme.destroy
      flash[:success] = t('.success')
    else
      flash[:error] = t('.error')
    end
    redirect_to category_themes_path
  end

  def vote_for
    current_user.vote_for(set_theme)
    voted?
  end

  def vote_against
    current_user.vote_against(set_theme)
    voted?
  end

  def revote
    current_user.unvote_for(set_theme)
    authorize @theme
    redirect_to :back, success: t('.success')
  end

  def current_city
    @city ||= get_current_city
  end

  def autocomplete
    render json: Theme.search(
      params[:term],
      fields: [{ title: :word_start }],
      where: { category_id: params[:category_id] }
    ).map(&:title)
  end

  private

  def set_theme
    @theme = @category.themes.find(params[:id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  def theme_params
    params.require(:theme).permit(:title, :content, :category_id, :city_id)
  end

  def voted?
    authorize @theme
    if @theme.voted_by?(current_user)
      redirect_to :back, success: t('.success')
    else
      redirect_to :back, error: t('.error')
    end
  end

  def get_current_city
    return City.find_by(id: session[:city_id]) if session[:city_id].present?

    city = City.find_by_ip(request.remote_ip)
    session[:city_id] = city.try(:id) if city

    city
  end

end

app/helpers/themes_helper.rb
module ThemesHelper

  def is_theme_owner?(theme)
    current_user == theme.user || current_user.admin? || current_user.moderator?
  end

  def add_theme(theme)
    theme.city_id = current_city.try(:id) if theme.city_id.blank? && current_city
    theme
  end

  def form_name_locale
    if cookies[:locale] == 'ru'
      :ru_name
    else
      :name
    end
  end

  def category_name_locale(category)
    if cookies[:locale] == 'ru'
      category.ru_name
    else
      category.name
    end
  end

end

app/views/themes/_form.html.slim
= t.association :city,
  label_method: form_name_locale,
  label: t('.choose_city'),
  include_blank: false,
  autofocus: true,
  input_html: { 'data-title' => t('.current_city'),
                'data-toggle' => 'tooltip',
                'data-placement' => 'top',
                class: 'blue-tooltip' }
= t.input :title
= t.input :content, as: :text, input_html: { rows: 5 }

app/views/themes/_search.html.slim
= form_tag category_themes_path, class: 'navbar-form search-form', role: 'search', method: :get do
  .input-group
    = text_field_tag :query,
            params[:query],
            class: 'form-control',
            id: 'search',
            placeholder: t('.search_problem'),
            required: true,
            data: { autocomplete_source: autocomplete_category_themes_path }

    .input-group-btn
      button.btn.btn-default.search type='submit'
        i.glyphicon.glyphicon-search
  - if params[:query].present?
    = link_to t('.clear'), category_themes_path, class: 'red clear'

app/views/themes/_theme.html.slim
.header.title.text-center
  h2
    = @theme.title

  - if current_user && (current_user.admin? || current_user.moderator?)
    .links.theme
      - if is_theme_owner?(@theme)
        = link_to '', edit_category_theme_path(@category, @theme), class: 'glyphicon glyphicon-pencil'
        = link_to '', category_theme_path(@category, @theme),
                method: :delete,
                data: { confirm: t('.delete') },
                class: 'glyphicon glyphicon-trash red'

  a.location href='https://www.google.ru/maps/place/#{@theme.city.name}'
    i.glyphicon.glyphicon-map-marker
    - if cookies[:locale] == 'ru'
      = @theme.city.ru_name
    - else
      = @theme.city.name

  .author
    = image_tag @theme.user.avatar.thumb, alt: "#{@theme.user.username}'s avatar", class: 'avatar small'
    = @theme.user.username

.content
  = @theme.content

app/views/themes/_votes.html.slim
.well
  .row.votes
    .col-md-12.text-center
      - if @theme.voted_by?(current_user)
        h3
          = t('.total_votes')
        .glyphicon.glyphicon-thumbs-up.thumbs-up
          div
            = @theme.votes_for
        .glyphicon.glyphicon-thumbs-down.thumbs-down
          div
            = @theme.votes_against
        = link_to t('.want_to_revote'), revote_category_theme_path(@category, @theme), method: :delete, class: 'revote red'
      - else
        h3
          = t('.how_is_this_problem')
        = link_to '', vote_for_category_theme_path(@category, @theme), method: :post, class: 'glyphicon glyphicon-thumbs-up thumbs-up'
        = link_to '', vote_against_category_theme_path(@category, @theme), method: :post, class: 'glyphicon glyphicon-thumbs-down thumbs-down'

app/views/themes/edit.html.slim
.row
  .col-sm-6.col-sm-offset-3
    h2.title.text-center
      = t('.edit')

    = simple_form_for [@category, add_theme(@theme)] do |t|
      = render partial: 'form', locals: {t: t}
      .text-center
        = t.submit t('buttons.update'), class: 'btn btn-success'
        = link_to t('buttons.back'), category_theme_path(@category, @theme), class: 'btn btn-default'

app/views/themes/index.html.slim
.row
  .col-md-12.text-center
    h2.title
      = t('.problems', category: category_name_locale(@category))
      = render 'themes/search'

.row
  .col-md-12.text-center

    - if @themes.empty?
      p.title
        = t('.no_problems')
      = link_to t('.create_first'), new_category_theme_path(@category), class: 'btn btn-success', type: 'button'

    - else
      .row
        - @themes.each do |theme|
          .col-md-6.thumbnail-wrapper
            .thumbnail
              = link_to category_theme_path(@category, theme) do
                .caption.text-center
                  .location
                    i.glyphicon.glyphicon-map-marker
                    - if cookies[:locale] == 'ru'
                      = theme.city.ru_name
                    - else
                      = theme.city.name

                  h4
                    = theme.title
                  small.text-muted
                    = t('.created', time: time_ago_in_words(theme.created_at))

      = paginate @themes

      = link_to t('.create'), new_category_theme_path(@category), class: 'btn btn-success', type: 'button'

    = link_to t('buttons.back'), categories_path,  class: 'btn btn-default'

app/views/themes/new.html.slim
.row
  .col-sm-6.col-sm-offset-3
    h2.title.text-center
      = t('.create')

    = simple_form_for [@category, add_theme(@theme)] do |t|
      = render partial: 'form', locals: {t: t}
      .text-center
        = t.submit t('buttons.create'), class: 'btn btn-success'
        = link_to t('buttons.back'), category_themes_path, class: 'btn btn-default'

app/views/themes/new_separate.html.slim
.row
  .col-sm-6.col-sm-offset-3
    h2.title.text-center
      = t('.create')

    = simple_form_for add_theme(@theme), url: create_separate_path, method: :post do |t|
      = t.association :city,
        label_method: form_name_locale,
        label: t('.choose_city'),
        include_blank: false,
        autofocus: true,
        input_html: { 'data-original-title' => t('.current_city'),
                      'data-toggle' =>'tooltip',
                      'data-placement' => 'top',
                      class: 'blue-tooltip' }
      = t.association :category, label_method: form_name_locale, label: t('.choose_category'), include_blank: false, required: true
      = t.input :title
      = t.input :content, as: :text, input_html: { rows: 5 }
      .text-center
        = t.submit t('buttons.create'), class: 'btn btn-success'
        = link_to t('buttons.back'), root_path, class: 'btn btn-default'

app/views/themes/show.html.slim
.row.problem-wrapper
  .col-md-12
    = render 'themes/theme'

  .col-md-6.col-md-offset-3
    - if current_user
      = render 'themes/votes'

.row.comments-wrapper
  - unless @theme.comments.empty?
    h3.title.text-center
      = t('.comments')
    .col-md-8.col-md-offset-2
      ul
        = render(partial: 'comments/comments_template', locals: { comments: @root_comments } )

  .col-md-6.col-md-offset-3.text-center
    - if current_user

      - if @theme.comments.empty?
        h3.title
          = t('.leave_first_comment')
      - else
        h3.title
          = t('.leave_comment')

      = simple_form_for [@category, @theme, Comment.new] do |t|
        = t.input :content, as: :text, input_html: { rows: 2 }, autofocus: true, label: false, placeholder: t('.content')
        = t.submit t('buttons.submit'), class: 'btn btn-success'

    - else
      h4.title
        = t('.want_to_leave_comments')
      span
        = link_to t('.sign_in'), new_user_session_path
        = t('.or')
        = link_to t('.sign_up'), new_user_registration_path
        | .