config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :categories, except: [:show] do
    resources :themes do
      member do
        post   :vote_for
        post   :vote_against
        delete :revote
      end
      collection do
       get :autocomplete
      end
      resources :comments, except: [:index, :show] do
        resources :subcomments, except: [:index, :show]
      end
    end
  end

  root 'pages#home'

  get 'themes/new', to: 'themes#new_separate', as: :new_separate
  post 'themes/create', to: 'themes#create_separate', as: :create_separate

  get '/statistics', to: 'pages#statistics', as: :statistics

  get '/change_locale/:locale', to: 'sessions#change_locale', as: :change_locale

  get '*path', to: redirect('/')

end

app/models/category.rb
class Category < ActiveRecord::Base

  mount_uploader :image, CategoryImageUploader

  belongs_to :user
  has_many   :themes, dependent: :destroy

  validates :name, :ru_name, presence: true, uniqueness: { case_sensitive: false }

  before_save :capitalize_name

  def capitalize_name
    self.name = name.capitalize
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authenticate_user!, except: [:index]
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = current_user.categories.new
    authorize @category
  end

  def edit;
    authorize @category
  end

  def create
    authorize Category
    @category = current_user.categories.new(category_params)

    if @category.save
      redirect_to categories_path, success: t('.success', category: category_locale(@category))
    else
      flash.now[:error] = t('.error')
      render :new
    end
  end

  def update
    authorize @category
    if @category.update(category_params)
      redirect_to category_themes_path(@category), success: t('.success', category: category_locale(@category))
    else
      flash.now[:error] = t('.error')
      render :edit
    end
  end

  def destroy
    authorize @category
    if @category.destroy
      flash[:success] = t('.success')
    else
      flash[:error] = t('.error')
    end
    redirect_to categories_path
  end

  private

  def category_locale(category)
    if cookies[:locale] == 'ru'
      category.ru_name
    else
      category.name
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :ru_name, :image)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper; end

app/views/categories/_form.html.slim
= c.input :name, autofocus: true
= c.input :ru_name
= c.input :image

app/views/categories/edit.html.slim
.row
  .col-sm-6.col-sm-offset-3
    h2.title.text-center
      = t('.edit')

    = simple_form_for @category do |c|
      = render partial: 'form', locals: { c: c }
      .text-center
        = c.submit t('buttons.update'), class: 'btn btn-success'
        = link_to t('buttons.back'), categories_path, class: 'btn btn-default'

app/views/categories/index.html.slim
- if @categories.empty?
  .row
    .col-md-12.text-center
      h2.title
        = t('.no_categories')
- else
  .row
    .col-md-12.text-center
      h2.title
        = t('.problem_categories')
  .row
    - @categories.each do |category|
      .col-lg-3.col-md-4.col-xs-6.thumbnail-wrapper
        .thumbnail
          = link_to category_themes_path(category) do
            = image_tag category.image.thumb, alt: "#{category.name} image"
            .caption.text-center
              h4
                - if cookies[:locale] == 'ru'
                  = category.ru_name
                - else
                  = category.name
              small.text-muted
                = t('.problem', count: category.themes.count)

          - if current_user && current_user.admin?
            .links.category
              = link_to '', edit_category_path(category), class: 'glyphicon glyphicon-pencil'
              = link_to '', category_path(category),
                method: :delete,
                data: { confirm: t('.delete') },
                class: 'glyphicon glyphicon-trash red'

- if current_user && current_user.admin?
  .row
    .col-md-12.text-center
      = link_to  t('.create'), new_category_path, class: 'btn btn-success'

app/views/categories/new.html.slim
.row
  .col-sm-6.col-sm-offset-3
    h2.title.text-center
      = t('.create')

    = simple_form_for @category do |c|
      = render partial: 'form', locals: { c: c }
      .text-center
        = c.submit t('buttons.create'), class: 'btn btn-success'
        = link_to t('buttons.back'), categories_path, class: 'btn btn-default'