config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :categories, except: [:show] do
    resources :themes do
      member do
        post   :vote_for
        post   :vote_against
        delete :revote
      end
      collection do
       get :autocomplete
      end
      resources :comments, except: [:index, :show] do
        resources :subcomments, except: [:index, :show]
      end
    end
  end

  root 'pages#home'

  get 'themes/new', to: 'themes#new_separate', as: :new_separate
  post 'themes/create', to: 'themes#create_separate', as: :create_separate

  get '/statistics', to: 'pages#statistics', as: :statistics

  get '/change_locale/:locale', to: 'sessions#change_locale', as: :change_locale

  get '*path', to: redirect('/')

end

app/views/layouts/_menu.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded='false' data-target='#menu' data-toggle='collapse' type='button'
        span.sr-only
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Vox Populi', root_path, class: 'navbar-brand'
    #menu.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right

        = render 'partials/locale'

        - if current_user
          li
            = link_to (content_tag(:i, '', class: 'glyphicon glyphicon glyphicon-globe') + t('menu.categories')).html_safe, categories_path
          li
            = link_to (content_tag(:i, '', class: 'glyphicon glyphicon-stats') + t('menu.statistics')).html_safe, statistics_path
          li.dropdown
            a.dropdown-toggle aria-expanded='false' aria-haspopup='true' data-toggle='dropdown' href="#" role='button'
              = image_tag current_user.avatar.thumb, alt: "User's avatar", class: 'avatar small'
            ul.dropdown-menu
              li
                = link_to (content_tag(:i, '', class: 'glyphicon glyphicon-tasks') + t('menu.profile')).html_safe, edit_user_registration_path

              - if current_user.admin?
                li
                  = link_to (content_tag(:i, '', class: 'glyphicon glyphicon-dashboard') + t('menu.administration')).html_safe, rails_admin_path
              li
                = link_to (content_tag(:i, '', class: 'glyphicon glyphicon-log-out') + t('menu.sign_out')).html_safe, destroy_user_session_path, method: :delete, class: 'red'
              li.divider role='separator'
        - else
          li
            = link_to (content_tag(:i, '', class: 'glyphicon glyphicon-log-in') + t('menu.sign_in')).html_safe, new_user_session_path

app/views/layouts/application.html.slim
doctype html
html lang="#{html_lang}" xmlns='http://www.w3.org/1999/xhtml'
  head
    meta charset='utf-8'
    meta name="viewport" content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'
    title Vox Populi

    - if cookies[:locale] == 'ru'
      javascript:
        var Chartkick = { 'language': 'ru' };
    - else
      javascript:
        var Chartkick = { 'language': 'en' };

    link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700|Lora&subset=latin,cyrillic' rel='stylesheet' type='text/css'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://www.google.com/jsapi', 'chartkick', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = render partial: 'layouts/menu'

    .container
      div id = 'notifications-wrapper'
        = flash_messages
      == yield

app/views/layouts/home.html.slim
doctype html
html lang="#{html_lang}" xmlns='http://www.w3.org/1999/xhtml'
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
    title Vox Populi

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body.pages

    .container
      div id = 'notifications-wrapper'
        = flash_messages
      == yield